
site_name: SparkFun GNSS Receiver Breakout - MAX-M10S (Qwiic) Hookup Guide
site_description: A hookup guide for the SparkFun GNSS Receiver Breakout - MAX-M10S (Qwiic)
site_url: https://sparkfun.github.io/SparkFun_u-blox_MAX-M10S

edit_uri: blob/main/docs/

repo_url: https://github.com/sparkfun/SparkFun_u-blox_MAX-M10S
repo_name: sparkfun/SparkFun_u-blox_MAX-M10S
copyright:
  Copyright 2023 - <a href="https://www.sparkfun.com/" target="_blank" rel="noopener">SparkFun Electronics&#174;<br>
  <a href="https://goo.gl/maps/vkstCpQZW6jZMjzYA" target="_blank" rel="noopener">6333 Dry Creek Parkway, Niwot, Colorado 80503</a>

# Configuration for webpage theme
theme:
  # Theme: https://squidfunk.github.io/mkdocs-material/
  name: material
  logo: assets/sfe_logo_sm.png
  palette:
    primary: grey
    accent: red
  # Page Font
  font:
    text: Roboto
    code: Roboto Mono

  # Features to Include (ref. theme documentation)
  features:
    # Enable copy button on code blocks
    - content.code.copy

    # Enable annotations in code blocks
    - content.code.annotate

    # Enable "view source" and "edit this page" buttons
    - content.action.edit

    # Enable Navigation buttons in the footer (i.e. previous/next)
    - navigation.footer


    # Enables anchor tracking (updates page url with the section user is on)
    # i.e. https://docs.sparkfun.com/<page link>/#<sub-section>
    - navigation.tracking

    # Enables tabs for navigating the website
    - navigation.tabs

    # Keeps tabs visible in the header when scrolling
    - navigation.tabs.sticky

    # Adds pop-up button just below the header (when the user starts to scroll up)
    # Allows users to easily jump to the beginning of the page
    - navigation.top

    # Renders path for page navigation at top of the page (makes page navigation more mobile friendly)
    - navigation.path

# Adds light/dark theme to webpage
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      accent: red
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: red
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  # Configures icons of callout boxes
  icon:
    # Sets repo icon to GitHub icon
    repo: fontawesome/brands/github

    # Admonition Icons (callout boxes)
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: simple/sparkfun
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      # Add custom admonitions
      github: simple/github
      arduino: simple/arduino
      python: simple/python
      code: fontawesome/regular/file-code
      terminal: octicons/terminal-16
      serial: fontawesome/solid/display
      hot: material/fire-alert
      # Permalink icon
      link: octicons/link-16

# Adds overrides for stylesheets, html, etc.
custom_dir: docs/overrides

# Included MkDocs plugins
# Add the installation of any new plugins to the ./github/workflows/mkdocs.yml file also
plugins:
  - search
  - typeset
  # Add revision date
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  # Add git committers at bottom of the page
  - git-committers:
      repository: sparkfun/SparkFun_Buck_Regulator_AP63357DV-7
      branch: main
  # Add git authors at bottom of the page
  - git-authors
  # Enables use of Git submodules and larger code base
  - monorepo
  # For PDF rendering
  - with-pdf:
      author: SparkFun Electronics&#174;
      copyright: Copyright 2023 - SparkFun Electronics&#174;
      cover_subtitle: none
      cover_logo: assets/img/sfe_logo_sm.png
      exclude_pages: [ "print_pdf", "file_issue", "contribute" ]
      output_path: ../assets/SparkFun_u-blox_GNSS_Receiver_Breakout_-_MAX-M10S_Hookup_Guide.pdf

# Included Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # base_path: ['./docs']
      url_download: true
      url_max_size: 0
      url_timeout: 0
      url_request_headers: {}
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - tables
  - admonition
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: ''

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/sparkfun
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sparkfun
    - icon: fontawesome/brands/github
      link: https://www.github.com/sparkfun
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SparkFun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sparkfun

# Configures styling for PDF rendering and webpage layout
extra_css:
  - stylesheet/extra.css

nav:
  - SparkFun GNSS Receiver Breakout - MAX-M10S (Qwiic) Hookup Guide:
    - Introduction: index.md
    - Hardware Overview: hardware_overview.md
    - Hardware Assembly: hardware_assembly.md
    - Software Setup and Programming: software_setup_and_programming.md
    - Example Code: example_code.md
  - Resources: resources_and_going_further.md
  - Support:
    - Troubleshooting: troubleshooting.md
    - Submit Issues: file_issue.md
    - Contribute: contribute.md
