
site_name: SparkFun MAX-M10S - Product Manual
site_description: A hookup guide for the SparkFun GNSS Receiver Breakout - MAX-M10S (Qwiic)
site_url: https://sparkfun.github.io/SparkFun_u-blox_MAX-M10S

edit_uri: edit/main/docs/

theme:
  name: material
  logo: img/sfe_logo_sm.png
  palette:
    primary: grey
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - monorepo

repo_url: https://github.com/sparkfun/SparkFun_u-blox_MAX-M10S/
repo_name: sparkfun/SparkFun_u-blox_MAX-M10S/

copyright: Copyright 2022 SparkFun Electronics (6333 Dry Creek Parkway, Niwot, Colorado 80503)

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - tables
  - admonition
  - md_in_html
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/sparkfun
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sparkfun
    - icon: fontawesome/brands/github
      link: https://www.github.com/sparkfun
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SparkFun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sparkfun

nav:
  - SparkFun_u-blox_MAX-M10S: index.md 
  - Hookup Guide: 
    - Hardware Overview: hardware_overview.md
    - Hardware Assembly: hardware_assembly.md
    - Software Setup and Programming: software_setup_and_programming.md
    - Troubleshooting Tips: troubleshooting_tips.md
    - Resources and Going Further: resources_and_going_further.md
